export const countriesCode = [
  {country: 'US dollar', code: 'USD'},
  {country: 'Japanese yen', code: 'JPY'},
  {country: 'Bulgarian lev', code: 'BGN'},
  {country: 'Czech koruna' , code: 'CZK'},
  {country: 'Danish krone', code: 'DKK'},
  {country: 'Pound sterling', code: 'GBP'},
  {country: 'Hungarian forint', code: 'HUF'},
  {country: 'Polish zloty', code: 'PLN'},
  {country: 'Romanian leu', code: 'RON'},
  {country: 'Swedish krona' , code: 'SEK'},
  {country: 'Swiss franc', code: 'CHF'},
  {country: 'Icelandic krona', code: 'ISK'},
  {country: 'Norwegian krone' , code: 'NOK'},
  {country: 'Croatian kuna', code: 'HRK'},
  {country: 'Russian rouble' , code: 'RUB'},
  {country: 'Turkish lira', code: 'TRY'},
  {country: 'Australian dollar', code: 'AUD'},
  {country: 'Brazilian real', code: 'BRL'},
  {country: 'Canadian dollar', code: 'CAD'},
  {country: 'Chinese yuan renminbi', code: 'CNY'},
  {country: 'Hong Kong dollar', code: 'HKD'},
  {country: 'Indonesian rupiah', code: 'IDR'},
  {country: 'Israeli shekel', code: 'ILS'},
  {country: 'Indian rupee' , code: 'INR'},
  {country: 'South Korean won', code: 'KRW'},
  {country: 'Mexican peso' , code: 'MXN'},
  {country: 'Malaysian ringgit', code: 'MYR'},
  {country: 'New Zealand dollar', code: 'NZD'},
  {country: 'Philippine peso' , code: 'PHP'},
  {country: 'Singapore dollar', code: 'SGD'},
  {country: 'Thai baht', code: 'THB'},
  {country: 'South African rand', code: 'ZAR'}
];

export const countries = [
  'US dollar',
  'Japanese yen',
  'Bulgarian lev',
  'Czech koruna' ,
  'Danish krone',
  'Pound sterling',
  'Hungarian forint',
  'Polish zloty',
  'Romanian leu',
  'Swedish krona' ,
  'Swiss franc',
  'Icelandic krona',
  'Norwegian krone' ,
  'Croatian kuna',
  'Russian rouble' ,
  'Turkish lira',
  'Australian dollar',
  'Brazilian real',
  'Canadian dollar',
  'Chinese yuan renminbi',
  'Hong Kong dollar',
  'Indonesian rupiah',
  'Israeli shekel',
  'Indian rupee' ,
  'South Korean won',
  'Mexican peso' ,
  'Malaysian ringgit',
  'New Zealand dollar',
  'Philippine peso' ,
  'Singapore dollar',
  'Thai baht',
  'South African rand'
];
